### PR TITLE
Ready to add to overall IP assembly

### PR DESCRIPTION
**Pull request by Reyna-5970**
I inserted all fasteners (except ones to balance platform, since I don't know its thickness -- but these will be M6 hex bolts) and reviewed each mounting hole. Decreased height of one of the pieces (block on horizontal axis) which was unnecessarily tall. Reviewed all mounting holes and replaced certain bolts with flathead bolts to be flush with the surface. This is a fairly complete first draft for the foot, just waiting on seeing how it all fits together

### CODE REVIEW

**Comment by jakechung42** [comment]
Some design critique:
image

I haven't run the numbers, so I don't know how much bending this would cause or how much vibration we have to damp out. I think we can go forward with this design and reiterate when we encounter problems. 

What are these gears for?
image

**Comment by Reyna-5970** [comment]
@jakechung42 Sounds good for your first point. I have a few ideas that I could easily implement if that becomes an issue. The gears in the second picture are for adding tension to the tendon strings, which cross underneath the main shaft and through the pink/purple pulleys.

**Comment by jakechung42** [comment]
image

Do you use a toolbox for your bolts and nuts? This part is suppresss in my copy of Solidworks. Do you see the same thing on yours?

**Comment by Reyna-5970** [comment]
No I don't use a toolbox, although McMaster-Carr sometimes provides files from older versions of solidworks, which might explain it

**Comment by Reyna-5970** [comment]
To add onto my previous message, it is not suppressed from my view

**Comment by jakechung42** [comment]
Alright, I think I know what is going on: Solidworks is referencing a file that is not in your GitHub local directory, so when I pull your model to my computer, I don't have that file for Solidworks to pull. When I try to unsuppress it, it links me to a local directory that is on your computer. I would copy that file (90576A102_ZINC-PLATED CLASS 8 STL NYLON-INSERT LOCKNUT (1).SLDPRT) and put it in the GitHub local directory. Make sure to change the Solidworks reference directory to refer to that file in the GitHub directory, not in your download folder.

**Comment by jakechung42** [comment]
Let me know if the message is clear. I'll try to rephrase it in a different way.

**Comment by Reyna-5970** [comment]
Whoops, you're right! I kept waiting to save McMaster-Carr files into my github directory because I kept changing the dimensions and was cluttering my space with new files (until I deleted them)... Looks like it finally caught up to me.

**Comment by Reyna-5970** [comment]
I should revise my first statement to the mechanical parts are basically complete, however, we still need to plan out the electrical layout and mount the components to the foot -- so not quite ready for printing.

**Comment by jakechung42** [comment]
Sounds good. Hopefull after Sunday, we will have a good idea on how to wire up the electrical parts.

**Pull request merged**
